# Generated by Django 4.1.2 on 2022-10-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('nickname', models.CharField(max_length=30)),
                ('pw', models.CharField(max_length=50)),
                ('birth', models.CharField(max_length=8)),
            ],
        ),
    ]
