import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Link from "next/link";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome NEXT-BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className={styles.next}>
          <h1>Welcome NEXT Blog</h1>
          <p>
            이 서비스는 저의 개발 실력 향상을 위해 만든 블로그입니다.
            <br />
            현재 아직 개발 중이나 마스터 피스 급으로 만드는 중이니 기대바랍니다.
          </p>
          <button>
            <Link href="/auth/signup">SIGN UP</Link>
          </button>
        </div>
      </main>
    </div>
  );
}
